version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    # TODO - gosec
    - unused
  settings:
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -SA1019
        - -ST1000
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: 'var-naming: don''t use ALL_CAPS in Go names; use CamelCase'
      - path: (.+)\.go$
        text: 'package-comments: should have a package comment'
      - path: (.+)\.go$
        text: 'exitAfterDefer:'
      - path: (.+)\.go$
        text: 'var-naming: avoid meaningless package names'
      - path: (.+)\.go$
        text: 'var-naming: avoid package names that conflict with Go standard library package names'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
