version: 2
project_name: kes

release:
  github:
    owner: kypello-io
    name: kes
  name_template: "v{{.Version}}"
  mode: append

builds:
  - main: ./cmd/kes
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/minio/kes/internal/sys.version={{.Version}}
      - -X github.com/minio/kes/internal/sys.commitID={{.FullCommit}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - vendor: Kypello
    homepage: https://github.com/kypello-io/kes
    maintainer: Kypello <dev@kypello.io>
    description: KES is a stateless and distributed key-management system for high-performance applications
    license: AGPL-3.0
    bindir: /usr/bin
    formats: [deb, rpm, apk]
    contents:
      - src: LICENSE
        dst: /usr/share/kes/LICENSE

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}
    signature: ${artifact}.sigstore.json

docker_signs:
  - cmd: cosign
    args: [sign, --yes, ${artifact}]
    artifacts: manifests

kos:
  - repositories:
      - ghcr.io/kypello-io/kes
    tags:
      - "{{.Version}}"
      - "{{.Tag}}"
      - latest
    bare: true
    base_image: cgr.dev/chainguard/static
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: none

sboms:
  - artifacts: archive

checksum:
  algorithm: sha256

changelog:
  disable: true
